"""Change primarykey

Revision ID: 200a1d6fba9e
Revises:
Create Date: 2025-09-25 20:10:56.483815

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "200a1d6fba9e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "moderators",
        sa.Column("telegram_id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("username", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("telegram_id"),
    )
    op.create_table(
        "ads",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=60), nullable=False),
        sa.Column("description", sa.String(length=800), nullable=False),
        sa.Column("link", sa.String(), nullable=False),
        sa.Column("is_moderating", sa.Boolean(), nullable=False),
        sa.Column("moderator_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["moderator_id"],
            ["moderators.telegram_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ads")
    op.drop_table("moderators")
    # ### end Alembic commands ###
